apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudsample
  name: cloudsample
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: cloudsample
  type: LoadBalancer