apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: amlxdWFuLmNoZW5AZ21haWwuY29t #jiquan.chen@gmail.com
  password: XjN3RWJWOVFy #^3wEbV9Qr
  serviceAccountEmail: Y2xvdWRzYW1wbGVhcHBAbGV2ZWwtYW1waG9yYS0yNzUxMDUuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20= #cloudsampleapp@level-amphora-275105.iam.gserviceaccount.com 